# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: nzbget.nzb
PackageVersion: "21.0"
PackageLocale: en-US
Publisher: NZBGet
PackageName: NZBGet
License: GPL-2.0 license
ShortDescription: Usenet downloader
ManifestType: defaultLocale
ManifestVersion: 1.5.0
