# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: nzbget.nzb
PackageVersion: "21.0"
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nzbget/nzbget/releases/download/v21.1/nzbget-21.1-bin-windows-setup.exe
  InstallerSha256: 536515CA1E57321C5DE664441D3394C4CD63C603183E257275188B3A9E168477
ManifestType: installer
ManifestVersion: 1.5.0
